import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    // {
    //     key: 'singleMenuItem',
    //     path: '/single-menu-view',
    //     title: 'Single menu item',
    //     translateKey: 'nav.singleMenuItem',
    //     icon: 'singleMenu',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [],
    //     subMenu: [],
    // },
    {
        key: 'groupMenu',
        path: '',
        title: 'Equipe',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'employees',
                path: '/employees',
                title: 'Funcionários',
                translateKey: '',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    {
        key: 'crm',
        path: '',
        title: 'CRM',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'attendanceToday',
                path: '/attendance-today',
                title: 'Prontuário do Dia',
                translateKey: '',
                icon: 'clipboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'appointmentFlow',
                path: '/appointment-flow',
                title: 'Fluxo de Atendimento',
                translateKey: '',
                icon: 'calendar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'calendar',
                path: '/calendar',
                title: 'Calendário',
                translateKey: '',
                icon: 'calendar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'patients',
                path: '/patients',
                title: 'Prontuários',
                translateKey: '',
                icon: 'clipboarList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'leads',
                path: '/leads',
                title: 'Funil de Vendas',
                translateKey: '',
                icon: 'funnel',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'finance',
        path: '',
        title: 'Financeiro',
        translateKey: '',
        icon: 'currencyDolar',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'financialAccounts',
                path: '/finance/accounts',
                title: 'Contas',
                translateKey: '',
                icon: 'wallet',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'cashFlowDashboard',
                path: '/cash-flow',
                title: 'Dashboard Financeiro',
                translateKey: '',
                icon: 'chartBar',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'cashClosing',
                path: '/cash-closing',
                title: 'Fechamento de Caixa',
                translateKey: '',
                icon: 'cash',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'accountsReceivable',
                path: '/accounts-receivable',
                title: 'Contas a Receber',
                translateKey: '',
                icon: 'arrowCircleDown',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'accountsPayable',
                path: '/accounts-payable',
                title: 'Contas a Pagar',
                translateKey: '',
                icon: 'arrowCircleUp',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'costCenterGoals',
                path: '/finance/cost-center-goals',
                title: 'Metas por Centro de Custo',
                translateKey: '',
                icon: 'flag',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'prostheticsNav',
        path: '',
        title: 'Próteses',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'prosthesis',
                path: '/prosthesis',
                title: 'Controle de Próteses',
                translateKey: '',
                icon: 'beaker',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'prosthesisTypes',
                path: '/prosthesis/types',
                title: 'Tipos de Prótese',
                translateKey: '',
                icon: 'clipboarList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'prosthesisLaboratories',
                path: '/prosthesis/laboratories',
                title: 'Laboratórios',
                translateKey: '',
                icon: 'clipboarList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'inventoryNav',
        path: '',
        title: 'Estoque',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'inventoryAdmin',
                path: '/inventory',
                title: 'Administração',
                translateKey: '',
                icon: 'cube',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventoryRequest',
                path: '/inventory/request',
                title: 'Solicitar',
                translateKey: '',
                icon: 'clipboardCheck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventorySuppliersNav',
                path: '/inventory/suppliers',
                title: 'Fornecedores',
                translateKey: '',
                icon: 'truck',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventoryCategoriesNav',
                path: '/inventory/categories',
                title: 'Categorias',
                translateKey: '',
                icon: 'tag',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'inventoryOperations',
                path: '/inventory/movements',
                title: 'Operações',
                translateKey: '',
                icon: 'clipboarList',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'config',
        path: '',
        title: 'Configurações',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'estabelecimento',
                path: '/settings/estabelecimento',
                title: 'Estabelecimento',
                translateKey: '',
                icon: 'officeBuilding',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'configs',
                path: '',
                title: 'Configurações',
                translateKey: '',
                icon: 'gear',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'consultationType',
                        path: '/consultation-type',
                        title: 'Tipos de Atendimento',
                        translateKey: '',
                        icon: 'clipboardCheck',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'catalog',
                        path: '/catalog',
                        title: 'Catálogos',
                        translateKey: '',
                        icon: 'bookOpen',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'service_product',
                        path: '/service-product',
                        title: 'Serviços & Produtos',
                        translateKey: '',
                        icon: 'shoppingBag',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'clinicProducts',
                        path: '/clinic-products',
                        title: 'Produtos da Clínica',
                        translateKey: '',
                        icon: 'archive',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'roleManagement',
                        path: '/settings',
                        title: 'Gerenciar Perfis',
                        translateKey: '',
                        icon: 'userGroup',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'settingsTemplates',
                        path: '/settings/templates',
                        title: 'Contratos e Receitas',
                        translateKey: '',
                        icon: 'documentText',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'operadoras',
                        path: '/settings/operadoras',
                        title: 'Operadoras de Convênio',
                        translateKey: '',
                        icon: 'briefcase',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'paymentMethods',
                        path: '/settings/payment-methods',
                        title: 'Meios de Pagamento',
                        translateKey: '',
                        icon: 'creditCard',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'rooms',
                        path: '/settings/rooms',
                        title: 'Salas',
                        translateKey: '',
                        icon: 'rooms',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'chartOfAccounts',
                        path: '/settings/chart-of-accounts',
                        title: 'Plano de Contas',
                        translateKey: '',
                        icon: 'bookOpen',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'comissionamento',
                        path: '/settings/comissionamento',
                        title: 'Comissionamento',
                        translateKey: '',
                        icon: 'percent',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'monitorSettings',
                        path: '/settings/monitor',
                        title: 'Monitor de Chamadas',
                        translateKey: '',
                        icon: 'monitor',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },
]

export default navigationConfig
